/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class can_data_t implements lcm.lcm.LCMEncodable
{
    public float q_abad[];
    public float q_hip[];
    public float q_knee[];
    public float qd_abad[];
    public float qd_hip[];
    public float qd_knee[];
 
    public can_data_t()
    {
        q_abad = new float[4];
        q_hip = new float[4];
        q_knee = new float[4];
        qd_abad = new float[4];
        qd_hip = new float[4];
        qd_knee = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc51e25da55f0463dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.can_data_t.class))
            return 0L;
 
        classes.add(lcmtypes.can_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.q_abad[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.q_hip[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.q_knee[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.qd_abad[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.qd_hip[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.qd_knee[a]); 
        }
 
    }
 
    public can_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public can_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.can_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.can_data_t o = new lcmtypes.can_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q_abad = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_abad[a] = ins.readFloat();
        }
 
        this.q_hip = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_hip[a] = ins.readFloat();
        }
 
        this.q_knee = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_knee[a] = ins.readFloat();
        }
 
        this.qd_abad = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.qd_abad[a] = ins.readFloat();
        }
 
        this.qd_hip = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.qd_hip[a] = ins.readFloat();
        }
 
        this.qd_knee = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.qd_knee[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.can_data_t copy()
    {
        lcmtypes.can_data_t outobj = new lcmtypes.can_data_t();
        outobj.q_abad = new float[(int) 4];
        System.arraycopy(this.q_abad, 0, outobj.q_abad, 0, 4); 
        outobj.q_hip = new float[(int) 4];
        System.arraycopy(this.q_hip, 0, outobj.q_hip, 0, 4); 
        outobj.q_knee = new float[(int) 4];
        System.arraycopy(this.q_knee, 0, outobj.q_knee, 0, 4); 
        outobj.qd_abad = new float[(int) 4];
        System.arraycopy(this.qd_abad, 0, outobj.qd_abad, 0, 4); 
        outobj.qd_hip = new float[(int) 4];
        System.arraycopy(this.qd_hip, 0, outobj.qd_hip, 0, 4); 
        outobj.qd_knee = new float[(int) 4];
        System.arraycopy(this.qd_knee, 0, outobj.qd_knee, 0, 4); 
        return outobj;
    }
 
}

