"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class actuator_response_t(object):
    __slots__ = ["id", "position", "velocity", "current"]

    __typenames__ = ["int64_t", "double", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.id = 0
        self.position = 0.0
        self.velocity = 0.0
        self.current = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(actuator_response_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.id, self.position, self.velocity, self.current))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != actuator_response_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return actuator_response_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = actuator_response_t()
        self.id, self.position, self.velocity, self.current = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if actuator_response_t in parents: return 0
        tmphash = (0x5506640baf43a4c5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if actuator_response_t._packed_fingerprint is None:
            actuator_response_t._packed_fingerprint = struct.pack(">Q", actuator_response_t._get_hash_recursive([]))
        return actuator_response_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", actuator_response_t._get_packed_fingerprint())[0]

